sudo: required
language: python

python:
  - "3.6"

addons:
  apt:
    packages:
      - clang
      - libglib2.0-dev

before_install:
  - apt-get update
  - apt-get install -y curl
  - rm -rf /var/lib/apt/lists/*
  - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - echo "deb http://download.mono-project.com/repo/ubuntu stable-trusty main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
  - apt-get update
  - apt-get install -y mono-complete
  - rm -rf /var/lib/apt/lists/* /tmp/*
  - pip install pycparser

install:
  - pip install codecov
  - pip install pytest pytest-cov pytest-asyncio
  - pip install -e .

script:
  - python -m pytest --cov=./

after_success:
  - codecov

deploy:
  provider: pypi
  user: siku2
  password:
    secure: st33VyBbTweHjqBN+l502ckde80sdEbGw6H4xd+lJaf8QwDU9mQmwtX8YIaVv2cMcrHa2evOaPhYHaZeqsp0HRL5/RuSuL69V8LloSf2XwRXZsPfJArSqUda07yyHdgRVYRNliOBixMFhpdPyegJGNG6IbeGGtqNRFjORKXN5sBR5jWAQRJLL5FhGVQ7vipDps/jWHyD2onLFr7P0GEq7Ijk+8ABSX08/aQxTifvyV3PF5wAgrFicKFKe3MXDhOEem5YKysmn1d4ykqBNZbDQRlzgESpQNuqMqKkzTHPiIuQ9U4IPnyPoKLkNOm9JS7NnaQ4fEY1+L4sXOyswGmv/n1dryoP+qbtmYq/pxnAJW/XSJ0SCQ9W08mCKnBgiBt2Mvi8jfU3yjR6BM3nbqFuCaKymdhsFslf4D2si5EfKaHT60qOwnYQ2EQW9c4+19Zrml1Q4tIfnNZye2+4KGSBZXZHhi9qvB+w/lekPS0wUJVcnWGdihaJEtTFA3RJ/4rjez73Pe+wNHCRZ1OW+xQ0srC/r8IWYFJjZ9pGEUlK3N2PMfMP3sIF2B0jMgWx7Xrjz/McS4C1JTgRRwkRyR5KVCsH/Gwquxgp9E9g2tTaeKfFd4jZ2ul8CRrDxqadwlU07wCLAuOUtlYGkGmQqt1Nc98vhKkCAllfMk4t9Uk9jok=
  on:
    tags: true
    branch: master