sudo: required
language: python
python:
- '3.6'
env:
- DISCORD_VERSION=discord.py
- DISCORD_VERSION=https://github.com/Rapptz/discord.py/archive/rewrite.zip
addons:
  apt:
    packages:
    - unzip
before_install:
- sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
- echo "deb http://download.mono-project.com/repo/ubuntu wheezy/snapshots/4.8.1 main"
  | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
- sudo apt-get update
- sudo apt-get install -y clang
- sudo apt-get install -y mono-complete
- sudo wget https://github.com/inkle/ink/releases/download/0.7.4/inklecate_windows_and_linux.zip
- cd $TRAVIS_BUILD_DIR
- unzip inklecate_windows_and_linux.zip
- chmod +x inklecate.exe
install:
- pip install -U setuptools
- pip install codecov
- pip install pytest pytest-cov pytest-asyncio
- pip install pycparser
- pip install $DISCORD_VERSION
- pip install -e .[ink,discord]
script:
- python -m pytest --cov=./
after_success:
- codecov
deploy:
  provider: pypi
  user: siku2
  password:
    secure: US7MG19B9g6qAMlxKicviErOsXx9whQkoxXSfX+y7u3p7/c5KbBMTw/d5p2Yl29D70qU2cEcWKIaoZPtltMvM1iKvqAQDW6RWwBR4jpvPV1lo1Iuxs95zqEJV6S9j8EmUAd7qCRgMV3yWGXYl0PG71HpA6rwBX/XaATD8hoTszir4GcwRpWmo/+noAL+XJvUG/BEhJNloRHemREHsrT5aAfWrUFtkjUNdp1bK2JbwpUH4uNZF++dGP6y4FRPCvpIdznt1y3/psktnZh6MVwZDatbheI/XforhlweYcJHWZLvy2SUkP1eyd5xfBJ06kUE6+ccpSWPeID/cWcGgXrCpDl5GEuidaY35laXvapMnU6OfmZ+PTUCGKJP4f3LxpFBgBoORg67aA9OjassfyuZkiTflc4OBcmGcdDglex/np3P1j59fS7dhXMmyl22z8XRJkz6Cu0UfPTe2/HWAAEJra7se22MEWD6XmC8lMoXm35gWsdDSRaYUDqkXqg/yJIXMy/CT/6Ry5OGl3qKv8QJUBT2A4e2oiR3G/9unSrMy0qUxqlCHQouaSzo/LJJc203KBDgvholNSox44UQZGJJoF2nosjLNl2P30LDJSI0j1Jj7pbDJTuWN6dQ+7NT+PSMd0ax74NjOV4zM5eCLO1E8Wq/mtAX5He5y99NtzktMOc=
  on:
    tags: true
    branch: master
