sudo: required
language: python

python:
  - "3.6"

env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
    - PYTHONUNBUFFERED=True

addons:
  apt:
    sources:
      - sourceline: deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main
        key_url: https://packages.microsoft.com/keys/microsoft.asc
      - sourceline: deb http://download.mono-project.com/repo/ubuntu trusty main
        key_url: http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xA6A19B38D3D831EF
    packages:
      - mono-devel
      - ca-certificates-mono
      - dotnet-hostfxr-2.0.0
      - dotnet-runtime-2.0.0
      - dotnet-sdk-2.0.0

before_install:
  - PY_LIBDIR=$(python -c 'import sysconfig; print(sysconfig.get_config_var("LIBDIR"))')
  - export LD_LIBRARY_PATH=$PY_LIBDIR:$LD_LIBRARY_PATH
  - pip install pycparser

install:
  - pip install codecov
  - pip install pytest pytest-cov pytest-asyncio
  - pip install -e .

script:
  - python -m pytest --cov=./

after_success:
  - codecov

deploy:
  provider: pypi
  user: siku2
  password:
    secure: st33VyBbTweHjqBN+l502ckde80sdEbGw6H4xd+lJaf8QwDU9mQmwtX8YIaVv2cMcrHa2evOaPhYHaZeqsp0HRL5/RuSuL69V8LloSf2XwRXZsPfJArSqUda07yyHdgRVYRNliOBixMFhpdPyegJGNG6IbeGGtqNRFjORKXN5sBR5jWAQRJLL5FhGVQ7vipDps/jWHyD2onLFr7P0GEq7Ijk+8ABSX08/aQxTifvyV3PF5wAgrFicKFKe3MXDhOEem5YKysmn1d4ykqBNZbDQRlzgESpQNuqMqKkzTHPiIuQ9U4IPnyPoKLkNOm9JS7NnaQ4fEY1+L4sXOyswGmv/n1dryoP+qbtmYq/pxnAJW/XSJ0SCQ9W08mCKnBgiBt2Mvi8jfU3yjR6BM3nbqFuCaKymdhsFslf4D2si5EfKaHT60qOwnYQ2EQW9c4+19Zrml1Q4tIfnNZye2+4KGSBZXZHhi9qvB+w/lekPS0wUJVcnWGdihaJEtTFA3RJ/4rjez73Pe+wNHCRZ1OW+xQ0srC/r8IWYFJjZ9pGEUlK3N2PMfMP3sIF2B0jMgWx7Xrjz/McS4C1JTgRRwkRyR5KVCsH/Gwquxgp9E9g2tTaeKfFd4jZ2ul8CRrDxqadwlU07wCLAuOUtlYGkGmQqt1Nc98vhKkCAllfMk4t9Uk9jok=
  on:
    tags: true
    branch: master