sudo: required
language: python
python:
- '3.6'
addons:
  apt:
    packages:
    - unzip
before_install:
- sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
- echo "deb http://download.mono-project.com/repo/ubuntu wheezy/snapshots/4.8.1 main"
  | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
- sudo apt-get update
- sudo apt-get install -y clang
- sudo apt-get install -y mono-complete
- sudo wget https://github.com/inkle/ink/releases/download/0.7.4/inklecate_windows_and_linux.zip
- cd $TRAVIS_BUILD_DIR
- unzip inklecate_windows_and_linux.zip
- chmod +x inklecate.exe
install:
- pip install -U setuptools
- pip install pycparser
- pip install codecov
- pip install pytest pytest-cov pytest-asyncio
- pip install -e .
script:
- python -m pytest --cov=./
after_success:
- codecov
deploy:
  provider: pypi
  user: siku2
  password:
    secure: SBjT5tNb3LVN0H7W2vJ+9mjnpFEWNjtUZ27G0yrLojfBYo4J0sbwo11nq7u4xJj3/zvYmEb8IoJEYGS49XuusU2bRVLgCWCEKsD3p7Jp1vkOrd2RK1MPiHwTE27Kjeo0Xp5IrfhlAP4MGtBYHBs73u6GWAekRPFr50I4SxTkm5CQH/ZjtkovNLKl+yPDg3QD1joePEm760U2foHd2K9+5dusKtFHRFQqlfK6/HUyCetZJJ2OYuKZJHhdI90oC+LlQ1AC85ZRjgFwBU1/933B5qHDaxcJ7XyNXHlz2Qujrwa9d7K6kXdulj61ak5yNpepKT3sZXPom4Rb882w9jBPf9S6QuUKExSqIzwTrGzv/L6h9b5Ln+9+ia79hi03l9o/kw3sRAzynH0JbSkvRSVwf2t4rA2t5Yh7+H88ou1OfEn5JzGKyzGhzSDwaAdSWfGk9X3XMEcrejMmm45/VThYjz9IrohFUi6kAaRAJwVMBjb1HF8qCYgvd7ofOx9lWXFikW0bO5Z8tT+Z94HCPs5YXn1cLUQvHgrjsK8KTqW0RTDBmPMLy0Zlt16kdt6IDszd7O0pM8KXAb8fFvg7+kkhNVCjZJTCX3pUEjOR2jZ7azbRCg4WDd3OndXcEz+8MqicP5jg7v1r/GKJr/zUMNoVH5nCp1LY/3nkrUuc6MdbcFs=
  on:
    tags: true
    branch: master
