# Dependencies
markdown:             kramdown
highlighter:          rouge

# Permalinks
permalink:            pretty

# Setup
title:                Eventory
tagline:              "A story telling framework"
description:          "In Development"
documentation_url:    http://eventory.readthedocs.io
url:                  https://siku2.github.io/Eventory
baseurl:              /

author:
  name:               "Simon Berger"
  url:                https://siku2.github.io/

paginate:             5

# Custom vars
version:              0.1.0

github:
  repo:               https://github.com/siku2/Eventory
