__title__ = "Eventory"
__description__ = "Framework for telling interactive stories!"
__url__ = "https://github.com/siku2/Eventory"
__version__ = "0.1.0"
__author__ = "siku2"
__author_email__ = "siku2@outlook.com"
__license__ = "MIT"
