__title__ = "Eventory"
__description__ = "Story time!"
__url__ = "https://github.com/siku2/Eventory"
__version__ = "0.0.4"
__author__ = "siku2"
__author_email__ = "siku2@outlook.com"
__license__ = "MIT"
